### PR TITLE
Set DATADOG_HOST according to DD_SITE or DD_DD_URL when MetricsProvider is enabled. Resolves #103

### LINKED ISSUE #103: Cluster Agent not honoring Site parameter when MetricsProvider is queried
**Describe what happened:**

I'm using Datadog Cluster Agent with `metricsProviderEnabled: true` and `Site: datadoghq.eu`

After configuring an HPA, I started seeing these errors:

```
2020-05-28 11:17:23 UTC | CLUSTER | ERROR | (pkg/util/kubernetes/autoscalers/datadogexternal.go:84 in queryDatadogExternal) | Error while executing metric query avg:eng_kyc_service.process.files.open{cluster_name:dev-eu-west-1-test,env:dev}.rollup(30): API error 403 Forbidden: {"errors": ["Invalid API key or Application key"]}
2020-05-28 11:17:23 UTC | CLUSTER | ERROR | (pkg/util/kubernetes/autoscalers/processor.go:80 in UpdateExternalMetrics) | Error getting metrics from Datadog: [Error while executing metric query avg:eng_kyc_service.process.files.open{cluster_name:dev-eu-west-1-test,env:dev}.rollup(30): API error 403 Forbidden: {"errors": ["Invalid API key or Application key"]}, strconv.Atoi: parsing "": invalid syntax]
```

I verified my credentials and they are valid, as long as you point to `datadoghq.eu`. Setting `DATADOG_HOST=https://app.datadoghq.eu` solved this.

**Describe what you expected:**

I would expect one of two things:
* `DATADOG_HOST` is populated from `DD_SITE` and `DD_DD_URL` when creating the Cluster Agent deployment
* Datadog Cluster Agent's client library leverages `DD_SITE` and `DD_DD_URL` to create the client.

**Steps to reproduce the issue:**

* Create a Datadog Cluster agent deployment with `datadoghq.eu` credentials and `metricsProviderEnablk
* Create an HPA using an external metric

**Additional environment details (Operating System, Cloud provider, etc):**

### PR DESCRIPTION
**Pull request by thehunt33r**
### What does this PR do?

This PR creates a `DATADOG_HOST` environment variable that is defined when `metricsProviderEnabled = true`, as the client used to fetch the metrics from Datadog doesn't recognize either `DD_SITE` or `DD_DD_URL`.

It:
* Create a const `DatadogHost` that corresponds to the `DATADOG_HOST` environment variable name
* Adds a `getDatadogHost` method to `pkg/controller/datadogagent/clusteragent.go`
* Creates the `DATADOG_HOST` environment variable when `metricsProviderEnabled` is true

### Motivation

Addressing issue #103

### Additional Notes

### CODE REVIEW

File: pkg/controller/datadogagent/clusteragent_test.go [hunk 1]
```diff
@@ -5,10 +5,12 @@ import (
 	"strconv"
 	"testing"
 
+	datadoghqv1alpha1 "github.com/DataDog/datadog-operator/pkg/apis/datadoghq/v1alpha1"
+	test "github.com/DataDog/datadog-operator/pkg/apis/datadoghq/v1alpha1/test"
+	"github.com/DataDog/datadog-operator/pkg/controller/utils/comparison"
```
Comment (clamoriniere) [inline pkg/controller/datadogagent/clusteragent_test.go:10]:
```suggestion
	"github.com/DataDog/datadog-operator/pkg/controller/utils/comparison"
	
```
