### PR TITLE
Fix issues with Secret management

### LINKED ISSUE #96: If appKeyExistingSecret is specified, then the token secret fails to create
**Output of the info page (if this is a bug)**
What is the info page??

**Describe what happened:**

I have setup my app key in a secret that I have created previously, called `secretapp`. I set up my cluster token in plain text under the `token` field. This is a snippet of my agent spec:

```
spec:
  credentials:
    apiKeyExistingSecret: secretapi
    appKeyExistingSecret: secretapp
    token: "<ThirtyX2XcharactersXlongXtoken>"
```

The cluster-agent fails to run, because it expects that the `secretapp` key to have a token key. 

```
  Warning  Failed     2s (x3 over 16s)  kubelet, kind-worker2  Error: couldn't find key token in Secret datadog/secretapp
```
**Describe what you expected:**

If the `token` key is not there, edit the secret and add the `token` key using the string passed in the `token` spec.

**Steps to reproduce the issue:**

Create an agent and cluster agent with the appkey passed as secret and try to pass a token:

```
spec:
  credentials:
    apiKeyExistingSecret: secretapi
    appKeyExistingSecret: secretapp
    token: "<ThirtyX2XcharactersXlongXtoken>"
```

### LINKED ISSUE #191: Mention required token for cluster agent
I just installed the datadog-operator into a cluster and for the most part the process was pretty straightforward, nice work on this!

However I did run into an issue getting the cluster-agent working: I didn't set a 'secret token' anywhere for the cluster-agent to use, which caused a `CreateContainerConfigError` error to throw from the cluster-agent complaining that `secret "datadog" not found`. I didn't realize it at first after reading through the installation/getting started docs, but a token is required and can be set in a secret called 'datadog' ([as mentioned here](https://docs.datadoghq.com/agent/cluster_agent/setup/?tab=secret#step-2---secure-cluster-agent-to-agent-communication)), or it can be set in the in `spec.credentials.token` field of the `DatadogAgent` config. Currently, I see that it is shown in [this example with the cluster agent](https://github.com/DataDog/datadog-operator/blob/master/examples/datadog-agent-with-clusteragent.yaml#L9), but not in [the 'all' example](https://github.com/DataDog/datadog-operator/blob/master/examples/datadog-agent-all.yaml). I feel like having to set this token should be called out more explicitly in the docs.

Separately, I did think it was kind of odd that the `api_key` and the `app_key` can be configured through the `DatadogAgent` to get the value from a secret (instead of setting the plain text value in the config), but the `token` [can only be set plainly in the config](https://github.com/DataDog/datadog-operator/blob/v0.4.0/config/crd/bases/v1/datadoghq.com_datadogagents.yaml#L7765) and can't be fetched from a secret. Was that intentional? That functionality might be nice too, so I could potentially just have one secret with my api/app keys and token for the cluster-agent.

### PR DESCRIPTION
**Pull request by L3n41c**
### What does this PR do?

Fix the following issues with Secret management:
* When a secret was provided for the API key but the APP key was provided in clear, the operator wrongly tried to create a secret for the APP key with the same name as the user-provided one for the API key.
* When a secret was provided for the API key and for the APP key, but the DCA token was not provided, the DCA pod manifest were referencing a secret for the token that was not created by the operator. The DCA pod were staying in `CreateContainerConfigError` state forever with a event saying `Error: secret "datadog" not found`.

### Motivation

Make things work!

### Additional Notes

Fixes #96
Fixes #191

### Describe your test plan

Try to create a `datadogagent` CR with the following `credentials` part:
```
spec:
  credentials:
    appKey: PUTYOUROWNHERE
    apiSecret:
      keyName: api_key
      secretName: my-datadog-secrets
```
The operator must spawn the agents properly instead of doing nothing and logging the following error:
```
{"level":"ERROR","ts":"2020-12-08T14:09:47Z","logger":"controller","msg":"Reconciler error","reconcilerGroup":"datadoghq.com","reconcilerKind":"DatadogAgent","controller":"datadogagent","name":"datadog","namespace":"datadog-operator-system","error":"secrets \"my-datadog-secrets\" already exists"}
```

Try to create a `datadogagent` CR with the following `credentials` part:
```
spec:
  credentials:
    appSecret:
      keyName: app_key
      secretName: my-datadog-secrets
    apiSecret:
      keyName: api_key
      secretName: my-datadog-secrets
```
The operator must spawn the agents properly instead of having DCA pods stuck in `CreateContainerConfigError` state with the following error: 
```
Events:
  Type     Reason          Age                  From               Message
  ----     ------          ----                 ----               -------
  Warning  Failed          109s (x9 over 2m8s)  kubelet            Error: secret "datadog" not found
```

### CODE REVIEW

File: controllers/datadogagent/secret.go [hunk 1]
```diff
@@ -33,17 +32,17 @@ func (r *Reconciler) manageAgentSecret(logger logr.Logger, dda *datadoghqv1alpha
 	}
 	now := metav1.NewTime(time.Now())
 	// checks token secret
-	secretName, _ := utils.GetAppKeySecret(dda)
```
Comment (clamoriniere) [inline controllers/datadogagent/secret.go:36]: the secret name is always equal to the `DatadogAgent.Name` ?

Comment (clamoriniere) [reply controllers/datadogagent/secret.go:36]: should we remove this function if it isn't used anymore

**Review by clamoriniere — COMMENTED** [review]
Could you try to add a unit-test that validate this fix?

File: controllers/datadogagent/secret.go (hunk 1 above)
Comment (L3n41c) [reply controllers/datadogagent/secret.go:36]: In fact, `utils.GetAppKeySecret(dda)` returns the secret that holds the APP key.
So, it can be:
* either the user-supplied secret if the user has setup `credentials.appSecret` in its `datadogagent` CR,
* or `DatadogAgent.Name` if the APP key is in the operator-managed secret if the user has setup `credentials.appKey` in its `datadogagent` CR.

So, `func GetAppKeySecret(…)` is used to build the agent manifest to setup the `DD_APP_KEY` environment variable.
But in this context, here, we need the name of the operator-managed secret and we don’t care whether the APP key as been provided in clear or in a user-supplied secret.

**Review by clamoriniere — APPROVED** [review]
